import dynamic from "next/dynamic";
import Head from "next/head";

const HomeMfe = dynamic(import("home/Home" as any));
const Header = dynamic(import("header/Header" as any));
const Footer = dynamic(import("footer/Footer" as any));

export default function Home() {
  return (
    <>
      <Head>
        <title>Host app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>This is the host code</div>
        <HomeMfe />
        <Header />
        <Footer />
      </main>
    </>
  );
}
